"""
NIST Cybersecurity Framework (CSF) controls mapped for small-organisation assessments.

Each control has:
  - control_ref : NIST-style identifier (e.g. ID.AM-1)
  - function    : one of Identify / Protect / Detect / Respond / Recover
  - category    : sub-category name
  - title       : short label
  - description : what the control requires
  - guidance    : practical advice for a small organisation
  - effort_band : Low / Medium / High — relative remediation effort
"""


def get_nist_controls():
    """Return a list of 45 NIST CSF controls suitable for small-org assessment."""
    return [
        # ── IDENTIFY (ID) ── 10 controls ──────────────────────────────
        {
            "control_ref": "ID.AM-1",
            "function": "Identify",
            "category": "Asset Management",
            "title": "Hardware Inventory",
            "description": "Physical devices and systems within the organisation are inventoried.",
            "guidance": "Maintain a spreadsheet or simple CMDB listing every laptop, server, router, and IoT device with owner, location, and purchase date.",
            "effort_band": "Low",
        },
        {
            "control_ref": "ID.AM-2",
            "function": "Identify",
            "category": "Asset Management",
            "title": "Software Inventory",
            "description": "Software platforms and applications within the organisation are inventoried.",
            "guidance": "List all installed applications, SaaS subscriptions, and licences. Use built-in OS tools or a simple audit script.",
            "effort_band": "Low",
        },
        {
            "control_ref": "ID.AM-3",
            "function": "Identify",
            "category": "Asset Management",
            "title": "Data Flow Mapping",
            "description": "Organisational communication and data flows are mapped.",
            "guidance": "Draw a simple diagram showing how data moves between systems, cloud services, and external partners.",
            "effort_band": "Medium",
        },
        {
            "control_ref": "ID.AM-4",
            "function": "Identify",
            "category": "Asset Management",
            "title": "External Information Systems",
            "description": "External information systems are catalogued.",
            "guidance": "Record every third-party service or cloud platform used (e.g. email provider, payment gateway, CRM).",
            "effort_band": "Low",
        },
        {
            "control_ref": "ID.BE-1",
            "function": "Identify",
            "category": "Business Environment",
            "title": "Role in Supply Chain",
            "description": "The organisation's role in the supply chain is identified and communicated.",
            "guidance": "Document who your suppliers and customers are and what data you exchange with them.",
            "effort_band": "Low",
        },
        {
            "control_ref": "ID.BE-2",
            "function": "Identify",
            "category": "Business Environment",
            "title": "Critical Service Identification",
            "description": "The organisation's place in critical infrastructure and its industry sector is identified.",
            "guidance": "Identify which of your services, if disrupted, would impact customers or partners most severely.",
            "effort_band": "Low",
        },
        {
            "control_ref": "ID.GV-1",
            "function": "Identify",
            "category": "Governance",
            "title": "Security Policy",
            "description": "Organisational cybersecurity policy is established and communicated.",
            "guidance": "Write a one-page security policy covering acceptable use, password rules, and incident escalation. Distribute to all staff.",
            "effort_band": "Medium",
        },
        {
            "control_ref": "ID.GV-2",
            "function": "Identify",
            "category": "Governance",
            "title": "Security Roles & Responsibilities",
            "description": "Cybersecurity roles and responsibilities are coordinated and aligned with internal roles.",
            "guidance": "Assign a security lead (even part-time) and document who is responsible for backups, patching, and incidents.",
            "effort_band": "Low",
        },
        {
            "control_ref": "ID.RA-1",
            "function": "Identify",
            "category": "Risk Assessment",
            "title": "Vulnerability Identification",
            "description": "Asset vulnerabilities are identified and documented.",
            "guidance": "Run periodic vulnerability scans using free tools (e.g. OpenVAS) or review vendor advisories monthly.",
            "effort_band": "Medium",
        },
        {
            "control_ref": "ID.RM-1",
            "function": "Identify",
            "category": "Risk Management Strategy",
            "title": "Risk Management Process",
            "description": "Risk management processes are established, managed, and agreed to by organisational stakeholders.",
            "guidance": "Create a simple risk register with likelihood, impact, and owner for each risk. Review quarterly.",
            "effort_band": "Medium",
        },
        # ── PROTECT (PR) ── 12 controls ───────────────────────────────
        {
            "control_ref": "PR.AC-1",
            "function": "Protect",
            "category": "Access Control",
            "title": "Identity & Credential Management",
            "description": "Identities and credentials are issued, managed, verified, revoked, and audited.",
            "guidance": "Use unique accounts per person, enforce strong passwords (12+ chars), and disable accounts when people leave.",
            "effort_band": "Low",
        },
        {
            "control_ref": "PR.AC-2",
            "function": "Protect",
            "category": "Access Control",
            "title": "Physical Access Control",
            "description": "Physical access to assets is managed and protected.",
            "guidance": "Lock server rooms and network closets. Use key cards or sign-in logs for sensitive areas.",
            "effort_band": "Low",
        },
        {
            "control_ref": "PR.AC-3",
            "function": "Protect",
            "category": "Access Control",
            "title": "Remote Access Management",
            "description": "Remote access is managed.",
            "guidance": "Require VPN for remote access to internal systems. Enable MFA on VPN and all cloud accounts.",
            "effort_band": "Medium",
        },
        {
            "control_ref": "PR.AC-4",
            "function": "Protect",
            "category": "Access Control",
            "title": "Least Privilege",
            "description": "Access permissions and authorisations are managed with least privilege.",
            "guidance": "Grant users only the access they need. Review permissions quarterly; revoke unused privileges.",
            "effort_band": "Medium",
        },
        {
            "control_ref": "PR.AC-5",
            "function": "Protect",
            "category": "Access Control",
            "title": "Multi-Factor Authentication",
            "description": "Multi-factor authentication is used for network and remote access.",
            "guidance": "Enable MFA on email, cloud admin consoles, and VPN. Use authenticator apps rather than SMS where possible.",
            "effort_band": "Low",
        },
        {
            "control_ref": "PR.AT-1",
            "function": "Protect",
            "category": "Awareness & Training",
            "title": "Security Awareness Training",
            "description": "All users are informed and trained.",
            "guidance": "Deliver short quarterly awareness sessions covering phishing, password hygiene, and social engineering. Track attendance.",
            "effort_band": "Medium",
        },
        {
            "control_ref": "PR.AT-2",
            "function": "Protect",
            "category": "Awareness & Training",
            "title": "Privileged User Training",
            "description": "Privileged users understand their roles and responsibilities.",
            "guidance": "Provide additional training for admins on secure configuration, logging, and incident handling.",
            "effort_band": "Medium",
        },
        {
            "control_ref": "PR.DS-1",
            "function": "Protect",
            "category": "Data Security",
            "title": "Data-at-Rest Protection",
            "description": "Data-at-rest is protected.",
            "guidance": "Enable full-disk encryption (BitLocker / FileVault) on all laptops and encrypt database backups.",
            "effort_band": "Medium",
        },
        {
            "control_ref": "PR.DS-2",
            "function": "Protect",
            "category": "Data Security",
            "title": "Data-in-Transit Protection",
            "description": "Data-in-transit is protected.",
            "guidance": "Enforce HTTPS/TLS on all web services. Use encrypted email for sensitive communications.",
            "effort_band": "Low",
        },
        {
            "control_ref": "PR.IP-1",
            "function": "Protect",
            "category": "Information Protection",
            "title": "Configuration Baselines",
            "description": "Baseline configurations of IT systems are created and maintained.",
            "guidance": "Document standard build images for workstations and servers. Harden defaults (disable unused ports/services).",
            "effort_band": "High",
        },
        {
            "control_ref": "PR.IP-4",
            "function": "Protect",
            "category": "Information Protection",
            "title": "Backups",
            "description": "Backups of information are conducted, maintained, and tested.",
            "guidance": "Automate daily backups (3-2-1 rule: 3 copies, 2 media types, 1 offsite). Test restores quarterly.",
            "effort_band": "Medium",
        },
        {
            "control_ref": "PR.MA-1",
            "function": "Protect",
            "category": "Maintenance",
            "title": "Maintenance & Repair",
            "description": "Maintenance and repair of organisational assets is performed and logged.",
            "guidance": "Schedule patch windows monthly. Log all hardware repairs and who performed them.",
            "effort_band": "Medium",
        },
        # ── DETECT (DE) ── 9 controls ─────────────────────────────────
        {
            "control_ref": "DE.AE-1",
            "function": "Detect",
            "category": "Anomalies & Events",
            "title": "Network Baseline",
            "description": "A baseline of network operations and expected data flows is established and managed.",
            "guidance": "Document normal traffic patterns and bandwidth usage. Flag deviations for investigation.",
            "effort_band": "High",
        },
        {
            "control_ref": "DE.AE-2",
            "function": "Detect",
            "category": "Anomalies & Events",
            "title": "Event Analysis",
            "description": "Detected events are analysed to understand attack targets and methods.",
            "guidance": "When alerts fire, record what was targeted, what technique was used, and document in an incident log.",
            "effort_band": "Medium",
        },
        {
            "control_ref": "DE.AE-3",
            "function": "Detect",
            "category": "Anomalies & Events",
            "title": "Event Correlation",
            "description": "Event data are collected and correlated from multiple sources.",
            "guidance": "Forward logs from firewalls, servers, and endpoints to a central location (even a shared folder or free SIEM).",
            "effort_band": "High",
        },
        {
            "control_ref": "DE.CM-1",
            "function": "Detect",
            "category": "Security Continuous Monitoring",
            "title": "Network Monitoring",
            "description": "The network is monitored to detect potential cybersecurity events.",
            "guidance": "Use the firewall's built-in logging and a free tool like Snort or Suricata for intrusion detection.",
            "effort_band": "High",
        },
        {
            "control_ref": "DE.CM-2",
            "function": "Detect",
            "category": "Security Continuous Monitoring",
            "title": "Physical Environment Monitoring",
            "description": "The physical environment is monitored to detect potential cybersecurity events.",
            "guidance": "Install cameras or access logs at server room entrances. Check environmental sensors (temperature, humidity).",
            "effort_band": "Medium",
        },
        {
            "control_ref": "DE.CM-3",
            "function": "Detect",
            "category": "Security Continuous Monitoring",
            "title": "Personnel Activity Monitoring",
            "description": "Personnel activity is monitored to detect potential cybersecurity events.",
            "guidance": "Enable user activity logging on critical systems. Review admin logins weekly. Establish a clear use-monitoring policy.",
            "effort_band": "Medium",
        },
        {
            "control_ref": "DE.CM-4",
            "function": "Detect",
            "category": "Security Continuous Monitoring",
            "title": "Malicious Code Detection",
            "description": "Malicious code is detected.",
            "guidance": "Deploy centrally managed anti-malware on every endpoint. Enable automatic signature updates.",
            "effort_band": "Low",
        },
        {
            "control_ref": "DE.DP-1",
            "function": "Detect",
            "category": "Detection Processes",
            "title": "Roles for Detection",
            "description": "Roles and responsibilities for detection are well defined.",
            "guidance": "Assign who reviews alerts, how often, and what the escalation path is. Document in the security policy.",
            "effort_band": "Low",
        },
        {
            "control_ref": "DE.DP-4",
            "function": "Detect",
            "category": "Detection Processes",
            "title": "Event Detection Communication",
            "description": "Event detection information is communicated.",
            "guidance": "Set up a shared channel (email group or chat) where detected events are reported immediately.",
            "effort_band": "Low",
        },
        # ── RESPOND (RS) ── 8 controls ─────────────────────────────────
        {
            "control_ref": "RS.RP-1",
            "function": "Respond",
            "category": "Response Planning",
            "title": "Incident Response Plan",
            "description": "An incident response plan is established and executed during or after an incident.",
            "guidance": "Write a 2-3 page incident response plan covering roles, communication, containment, and evidence preservation. Test it annually.",
            "effort_band": "Medium",
        },
        {
            "control_ref": "RS.CO-1",
            "function": "Respond",
            "category": "Communications",
            "title": "Personnel Know Their Roles",
            "description": "Personnel know their roles and order of operations when a response is needed.",
            "guidance": "Create a one-page quick-reference card with names, phone numbers, and escalation steps. Post it visibly.",
            "effort_band": "Low",
        },
        {
            "control_ref": "RS.CO-2",
            "function": "Respond",
            "category": "Communications",
            "title": "Incident Reporting",
            "description": "Incidents are reported consistent with established criteria.",
            "guidance": "Define what constitutes a reportable incident and ensure staff know how to report (e.g. email security@, phone call).",
            "effort_band": "Low",
        },
        {
            "control_ref": "RS.CO-3",
            "function": "Respond",
            "category": "Communications",
            "title": "Information Sharing",
            "description": "Information is shared consistent with response plans.",
            "guidance": "Agree in advance what information can be shared externally (regulator, customers, press) and by whom.",
            "effort_band": "Medium",
        },
        {
            "control_ref": "RS.AN-1",
            "function": "Respond",
            "category": "Analysis",
            "title": "Investigation Notifications",
            "description": "Notifications from detection systems are investigated.",
            "guidance": "Triage every alert within 24 hours. Document findings even if the alert is a false positive.",
            "effort_band": "Medium",
        },
        {
            "control_ref": "RS.AN-2",
            "function": "Respond",
            "category": "Analysis",
            "title": "Incident Impact Understanding",
            "description": "The impact of the incident is understood.",
            "guidance": "Assess which systems and data are affected, estimate downtime, and determine if customer data is at risk.",
            "effort_band": "Medium",
        },
        {
            "control_ref": "RS.MI-1",
            "function": "Respond",
            "category": "Mitigation",
            "title": "Incident Containment",
            "description": "Incidents are contained.",
            "guidance": "Isolate affected systems from the network immediately. Have pre-approved procedures for disconnecting compromised machines.",
            "effort_band": "Medium",
        },
        {
            "control_ref": "RS.IM-1",
            "function": "Respond",
            "category": "Improvements",
            "title": "Lessons Learned",
            "description": "Response plans incorporate lessons learned.",
            "guidance": "Hold a post-incident review within one week. Update the incident response plan with findings.",
            "effort_band": "Low",
        },
        # ── RECOVER (RC) ── 6 controls ─────────────────────────────────
        {
            "control_ref": "RC.RP-1",
            "function": "Recover",
            "category": "Recovery Planning",
            "title": "Recovery Plan Execution",
            "description": "A recovery plan is executed during or after a cybersecurity incident.",
            "guidance": "Document step-by-step recovery procedures for critical systems (e.g. rebuild server, restore from backup). Test annually.",
            "effort_band": "High",
        },
        {
            "control_ref": "RC.RP-2",
            "function": "Recover",
            "category": "Recovery Planning",
            "title": "Recovery Plan Update",
            "description": "Recovery plan is updated after incidents and exercises.",
            "guidance": "After each test or real incident, update the plan with what worked and what did not.",
            "effort_band": "Low",
        },
        {
            "control_ref": "RC.IM-1",
            "function": "Recover",
            "category": "Improvements",
            "title": "Recovery Strategy Improvement",
            "description": "Recovery planning and processes are improved by incorporating lessons learned.",
            "guidance": "Review recovery metrics (RTO/RPO) after exercises and adjust resources or procedures to close gaps.",
            "effort_band": "Medium",
        },
        {
            "control_ref": "RC.IM-2",
            "function": "Recover",
            "category": "Improvements",
            "title": "Recovery Strategy Update",
            "description": "Recovery strategies are updated.",
            "guidance": "Revisit the recovery strategy when major systems change (new cloud service, new office, staff turnover).",
            "effort_band": "Low",
        },
        {
            "control_ref": "RC.CO-1",
            "function": "Recover",
            "category": "Communications",
            "title": "Public Relations Management",
            "description": "Public relations are managed.",
            "guidance": "Prepare a template press statement and designate a single spokesperson. Coordinate with legal before public disclosure.",
            "effort_band": "Medium",
        },
        {
            "control_ref": "RC.CO-2",
            "function": "Recover",
            "category": "Communications",
            "title": "Reputation Recovery",
            "description": "Reputation is repaired after an incident.",
            "guidance": "Proactively communicate remediation steps to affected customers. Publish a brief lessons-learned summary.",
            "effort_band": "Medium",
        },
    ]
